<?php
/**
 * @file
 * Saving dinosaurs and food to DB.
 */

/**
 * Defines path to directory with dinosaurs pictures.
 */
define('DINO_PICTURE_DIR', drupal_get_path('theme', 'dino') . '/images/dino');
/**
 * Defines path to directory with food pictures.
 */
define('FOOD_PICTURE_DIR', drupal_get_path('theme', 'dino') . '/images/food');
/**
 * Defines path to directory with jurassic dinosaurs pictures.
 */
define('JURASSIC_PICTURE_DIR', drupal_get_path('theme', 'dino') . '/images/jurassic');

/**
 * Defined this module path.
 */
define('BATCH_ITEMS_MODULE_PATH', drupal_get_path('module', 'batch_items'));

require_once BATCH_ITEMS_MODULE_PATH . '/includes/dinosaurs.inc';
require_once BATCH_ITEMS_MODULE_PATH . '/includes/food.inc';
require_once BATCH_ITEMS_MODULE_PATH . '/includes/jurassic.inc';

/**
 * Implements hook_menu().
 */
function batch_items_menu() {
  $weight = 10;

  return [
    'admin/settings/batch' => [
      'title' => 'Batch',
      'page callback' => 'drupal_get_form',
      'page arguments' => ['batch_items_form'],
      'access arguments' => ['administer content'],
      'weight' => $weight++,
    ],
  ];
}

/**
 * Form with button for batch starting.
 *
 * @param $form
 * @param $form_state
 *
 * @return mixed
 */
function batch_items_form($form, &$form_state) {
  $dino_default_count = count(_get_dinosaurs());
  $food_default_count = count(_get_food());
  $jurassic_default_count = count(_get_jurassic_dinosaurs());

  $result = db_select('eck_dinosaur', 'd')
    ->fields('d')
    ->execute();
  $dino_db_count = $result->rowCount();
  $result = db_select('eck_food', 'f')
    ->fields('f')
    ->execute();
  $food_db_count = $result->rowCount();
  $result = db_select('eck_jurassic', 'j')
    ->fields('j')
    ->execute();
  $jurassic_db_count = $result->rowCount();

  drupal_get_messages();
  drupal_set_message(t('@d dinosaurs in DB now.', ['@d' => $dino_db_count]));
  drupal_set_message(t('@f food in DB now.', ['@f' => $food_db_count]));
  drupal_set_message(t('@j jurassic dinosaurs in DB now.', ['@j' => $jurassic_db_count]));

  $form['add'] = [
    '#type' => 'submit',
    '#value' => t('Add dinosaurs, food and jurassic'),
    '#submit' => ['batch_items_add'],
  ];
  if ($dino_default_count <= $dino_db_count && $food_default_count <= $food_db_count && $jurassic_default_count <= $jurassic_db_count) {
    $form['add']['#disabled'] = TRUE;
  }

  $form['remove'] = [
    '#type' => 'submit',
    '#value' => t('Remove all dinosaurs, food and jurassic'),
    '#submit' => ['batch_items_remove'],
  ];

  return $form;
}

/**
 * Add all dinosaurs, food and jurassic to DB from code.
 */
function batch_items_add() {
  $operations = [];

  foreach (_get_dinosaurs() as $i => $dinosaur) {
    $operations[] = [
      'batch_items_dinosaurs_batch',
      [
        $dinosaur,
        t('(Operation @operation)', ['@operation' => $i]),
      ],
    ];
  }
  foreach (_get_food() as $i => $food) {
    $operations[] = [
      'batch_items_food_batch',
      [
        $food,
        t('(Operation @operation)', ['@operation' => $i]),
      ],
    ];
  }
  foreach (_get_jurassic_dinosaurs() as $i => $jurassic_dinosaur) {
    $operations[] = [
      'batch_items_jurassic_batch',
      [
        $jurassic_dinosaur,
        t('(Operation @operation)', ['@operation' => $i]),
      ],
    ];
  }

  $batch = [
    'operations' => $operations,
    'finished' => 'batch_items_batch_finished',
  ];

  batch_set($batch);
}

/**
 * Batch operations with dinosaurs.
 */
function batch_items_dinosaurs_batch($dinosaur, $operation_details, &$context) {
  $entity = entity_create('dinosaur', ['type' => 'dinosaur']);
  $wrapper = entity_metadata_wrapper('dinosaur', $entity);
  $wrapper->picture->set($dinosaur['picture']);
  $wrapper->name->set($dinosaur['name']);
  $wrapper->grade->set($dinosaur['grade']);
  $wrapper->food_type->set($dinosaur['food_type']);
  $wrapper->favorite_food->set($dinosaur['favorite_food']);
  $wrapper->consume->set($dinosaur['consume']);
  $wrapper->save();

  $context['results']['count']++;
}

/**
 * Batch operations with food.
 */
function batch_items_food_batch($food, $operation_details, &$context) {
  $entity = entity_create('food', ['type' => 'food']);
  $wrapper = entity_metadata_wrapper('food', $entity);
  $wrapper->picture->set($food['picture']);
  $wrapper->food_type->set($food['food_type']);
  $wrapper->name->set($food['name']);
  $wrapper->save();

  $context['results']['count']++;
}

/**
 * Batch operations with jurassic.
 */
function batch_items_jurassic_batch($jurassic, $operation_details, &$context) {
  $entity = entity_create('jurassic', ['type' => 'jurassic']);
  $wrapper = entity_metadata_wrapper('jurassic', $entity);
  $wrapper->pictures->set(implode(',', $jurassic['pictures']));
  $wrapper->name->set($jurassic['name']);
  $wrapper->consume->set($jurassic['consume']);
  $wrapper->description->set($jurassic['description']);
  $wrapper->price->set($jurassic['price']);
  $wrapper->save();

  $context['results']['count']++;
}

/**
 * Batch finish function.
 *
 * @param $success
 * @param $results
 * @param $operations
 */
function batch_items_batch_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message(
      format_plural(
        $results['count'],
        '1 element was created.',
        '@count elements were created.'
      )
    );
  }
  else {
    $error_operation = reset($operations);
    drupal_set_message(
      t('An error occurred while processing @operation with arguments : @args',
        [
          '@operation' => $error_operation[0],
          '@args' => print_r($error_operation[0], TRUE),
        ]
      ),
      'error'
    );
  }
}

/**
 * Remove all dinosaurs, food and jurassic from DB.
 */
function batch_items_remove() {
  db_truncate('eck_dinosaur')->execute();
  db_truncate('eck_food')->execute();
  db_truncate('eck_jurassic')->execute();
}
