<?php
/**
 * @file
 * Module's main file.
 */

/**
 * Defines site main theme name.
 */
define('DINO_THEME_NAME', 'dino');

/**
 * Implements hook_block_info_alter().
 */
function dino_core_block_info_alter(&$blocks, $theme, $code_blocks) {
  // Configure default blocks.
  $blocks['system']['navigation']['status'] = FALSE;
  $blocks['system']['powered-by']['status'] = FALSE;
  $blocks['user']['login']['region'] = 'content';
}

/**
 * Implements hook_schema_alter().
 */
function dino_core_schema_alter(&$schema) {
  $schema['users']['fields']['timer'] = [
    'description' => 'The Unix timestamp saved time when the timer should be completed.',
    'type' => 'int',
    'not null' => TRUE,
    'default' => 0,
  ];
  $schema['users']['fields']['catch'] = [
    'description' => 'Food ID indicates whether the bait is put.',
    'type' => 'int',
    'size' => 'tiny',
    'not null' => TRUE,
    'default' => 0,
  ];
  $schema['users']['fields']['dinosaurs'] = [
    'type' => 'text',
    'size' => 'normal',
    'not null' => FALSE,
    'description' => 'Dinosaurs ID\'s opened by user.',
  ];
  $schema['users']['fields']['food'] = [
    'type' => 'text',
    'size' => 'normal',
    'not null' => FALSE,
    'description' => 'Food ID\'s received by user.',
  ];
}

/**
 * Implements hook_mail_alter().
 */
function dino_core_mail_alter(&$message) {
  // Not need to send any emails for this project.
  $message['send'] = FALSE;
}
